Personal Blog Management System/Areas/Admin/ViewModels/Posts.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using PersonalBlogManagementSystem.Infrastructure;
using PersonalBlogManagementSystem.Models;

namespace PersonalBlogManagementSystem.Areas.Admin.ViewModels
{
    public class TagCheckbox
    {
        public int? Id { get; set; }
        public string Name { get; set; }
        public bool IsChecked { get; set; }
    }

    public class PostsIndex
    {
        public PagedData<Post> Posts { get; set; }
    }

    public class PostsForm
    {
        public bool IsNew { get; set; }
        public int? PostId { get; set; }

        [Required, MaxLength(128)]
        public string Title { get; set; }

        [Required, MaxLength(128)]
        public string Slug { get; set; }

        [Required, DataType(DataType.MultilineText)]
        public string Content { get; set; }

        public IList<TagCheckbox> Tags { get; set; }
    }
}

Personal Blog Management System/Models/Post.cs
using System;
using System.Collections.Generic;
using NHibernate.Mapping.ByCode;
using NHibernate.Mapping.ByCode.Conformist;


namespace PersonalBlogManagementSystem.Models
{
    public class Post
    {
        public virtual int Id { get; set; }
        public virtual User User { get; set; }

        public virtual string Title { get; set; }
        public virtual string Slug { get; set; }
        public virtual string Content { get; set; }

        public virtual DateTime Created { get; set; }
        public virtual DateTime? Updated { get; set; }
        public virtual DateTime? Deleted { get; set; }

        public virtual IList<Tag> Tags { get; set; }

        public virtual bool IsDeleted { get { return Deleted != null; } }

        public Post()
        {
            Tags = new List<Tag>();
        }
    }

    public class PostMap : ClassMapping<Post>
    {
        public PostMap()
        {
            Table("posts");

            Id(x => x.Id, x => x.Generator(Generators.Identity));

            ManyToOne(x => x.User, x =>
                {
                    x.Column("userid");
                    x.NotNullable(true);
                });

            Property(x => x.Title, x => x.NotNullable(true));
            Property(x => x.Slug, x => x.NotNullable(true));
            Property(x => x.Content, x => x.NotNullable(true));

            Property(x => x.Created, x => x.NotNullable(true));
            Property(x => x.Updated, x => x.NotNullable(false));
            Property(x => x.Deleted, x => x.NotNullable(false));

            Bag(x => x.Tags, x =>
            {
                x.Key(y => y.Column("postid"));
                x.Table("post_tags");
            }, x => x.ManyToMany(y => y.Column("tagid")));
        }
    }
}

Personal Blog Management System/ViewModels/Posts.cs
using PersonalBlogManagementSystem.Infrastructure;
using PersonalBlogManagementSystem.Models;

namespace PersonalBlogManagementSystem.ViewModels
{
    public class PostsIndex
    {
        public PagedData<Post> Posts { get; set; }
    }

    public class PostsShow
    {
        public Post Post { get; set; }
    }

    public class PostsTag
    {
        public Tag Tag { get; set; }
        public PagedData<Post> Posts { get; set; }
    }
}

Personal Blog Management System/Areas/Admin/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using NHibernate.Linq;
using PersonalBlogManagementSystem.Areas.Admin.ViewModels;
using PersonalBlogManagementSystem.Infrastructure;
using PersonalBlogManagementSystem.Infrastructure.Extensions;
using PersonalBlogManagementSystem.Models;

namespace PersonalBlogManagementSystem.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    [SelectedTabAttribute("posts")]
    public class PostsController : Controller
    {
        private const int PostsPerPage = 5;

        public ActionResult Index(int page = 1)
        {
            var totalPostsCount = Database.Session.Query<Post>().Count();

            var baseQuery = Database.Session.Query<Post>().OrderByDescending(f => f.Created);

            var postIds = baseQuery
                .Skip((page - 1) * PostsPerPage)
                .Take(PostsPerPage)
                .Select(p => p.Id)
                .ToArray();

            var currentPostsPage = baseQuery
                .Where(p => postIds.Contains(p.Id))
                .FetchMany(f => f.Tags)
                .Fetch(f => f.User)                                        
                .ToList();


            return View(new PostsIndex
            {
                Posts = new PagedData<Post>(currentPostsPage, totalPostsCount, page, PostsPerPage)
            });
        }

        public ActionResult New()
        {
            return View("Form", new PostsForm
            {
                IsNew = true,
                Tags = Database.Session.Query<Tag>().Select(tag => new TagCheckbox
                {
                    Id = tag.Id,
                    Name = tag.Name,
                    IsChecked = false
                }).ToList()
            });
        }

        public ActionResult Edit(int id)
        {
            var post = Database.Session.Load<Post>(id);

            if (post == null)
                return HttpNotFound();

            return View("Form", new PostsForm
                {
                    IsNew = false,
                    PostId = id,
                    Content = post.Content,
                    Slug = post.Slug,
                    Title = post.Title,
                    Tags = Database.Session.Query<Tag>().Select(tag => new TagCheckbox
                    {
                        Id = tag.Id,
                        Name = tag.Name,
                        IsChecked = post.Tags.Contains(tag)
                    }).ToList()
                });
        }

        [HttpPost, ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult Form(PostsForm form)
        {
            form.IsNew = form.PostId == null;

            if (!ModelState.IsValid)
                return View(form);

            var selectedTags = ReconcileTags(form.Tags).ToList();

            Post post;

            if (form.IsNew)
            {
                post = new Post
                {
                    Created = DateTime.UtcNow,
                    User = Auth.User
                };

                foreach (var tag in selectedTags)
                    post.Tags.Add(tag);
            }
            else
            {
                post = Database.Session.Load<Post>(form.PostId);

                if (post == null)
                    return HttpNotFound();

                post.Updated = DateTime.UtcNow;

                foreach (var toAdd in selectedTags.Where(t => !post.Tags.Contains(t)))
                    post.Tags.Add(toAdd);

                foreach (var toRemove in post.Tags.Where(t => !selectedTags.Contains(t)).ToList())
                    post.Tags.Remove(toRemove);
            }

            post.Title = form.Title;
            post.Slug = form.Slug;
            post.Content = form.Content;

            Database.Session.SaveOrUpdate(post);

            return RedirectToAction("Index");
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Trash(int id)
        {
            var post = Database.Session.Load<Post>(id);

            if (post == null)
                return HttpNotFound();

            post.Deleted = DateTime.UtcNow;
            Database.Session.Update(post);


            return RedirectToAction("Index");
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var post = Database.Session.Load<Post>(id);

            if (post == null)
                return HttpNotFound();

            Database.Session.Delete(post);

            return RedirectToAction("Index");
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Restore(int id)
        {
            var post = Database.Session.Load<Post>(id);

            if (post == null)
                return HttpNotFound();

            post.Deleted = null;
            Database.Session.Update(post);

            return RedirectToAction("Index");
        }


        private IEnumerable<Tag> ReconcileTags(IList<TagCheckbox> tags)
        {
            foreach (var tag in tags.Where(t => t.IsChecked))
            {
                if (tag.Id != null)
                {
                    yield return Database.Session.Load<Tag>(tag.Id);
                    continue;
                }

                var existingTag = Database.Session.Query<Tag>().FirstOrDefault(t => t.Name == tag.Name);
                if (existingTag != null)
                {
                    yield return existingTag;
                    continue;
                }

                var newTag = new Tag
                {
                    Name = tag.Name,
                    Slug = tag.Name.Slugify()
                };

                Database.Session.Save(newTag);
                yield return newTag;
            }

            
        }
    }
}

Personal Blog Management System/Controllers/PostsController.cs
using System.Web.Mvc;
using System.Linq;
using NHibernate.Linq;
using PersonalBlogManagementSystem.Models;
using PersonalBlogManagementSystem.ViewModels;
using PersonalBlogManagementSystem.Infrastructure;
using System.Text.RegularExpressions;
using System;

namespace PersonalBlogManagementSystem.Controllers
{
    public class PostsController : Controller
    {
        private const int PostsPerPage = 5;

        public ActionResult Index(int page = 1)
        {
            var baseQuery = Database.Session.Query<Post>()
                .Where(p => p.Deleted == null)
                .OrderByDescending(p => p.Created);

            var totalPostCount = baseQuery.Count();
            var postIds = baseQuery.Skip((page - 1) * PostsPerPage)
                .Take(PostsPerPage)
                .Select(t => t.Id)
                .ToArray();

            var posts = baseQuery.Where(t => postIds.Contains(t.Id))
                .FetchMany(t => t.Tags)
                .Fetch(t => t.User)
                .ToList();

            return View(new PostsIndex
                {
                    Posts = new PagedData<Post>(posts, totalPostCount, page, PostsPerPage)
                });
        }

        public ActionResult Tag(string idAndSlug, int page = 1)
        {
            var parts = SeperateIdAndSlug(idAndSlug);

            if (parts == null)
                return HttpNotFound();

            var tag = Database.Session.Load<Tag>(parts.Item1);
            if (tag == null)
                return HttpNotFound();

            if (!tag.Slug.Equals(parts.Item2, StringComparison.CurrentCultureIgnoreCase))
                return RedirectToRoutePermanent("Tag", new { id = parts.Item1, slug = tag.Slug });

            var totalPostCount = tag.Posts.Count();
            var postIds = tag.Posts
                .OrderByDescending(g => g.Created)
                .Skip((page - 1) * PostsPerPage)
                .Take(PostsPerPage)
                .Where(t => t.Deleted == null)
                .Select(t => t.Id)
                .ToArray();

            var posts = Database.Session.Query<Post>()
                .OrderByDescending(b => b.Created)
                .Where(b => postIds.Contains(b.Id))
                .FetchMany(f => f.Tags)
                .Fetch(f => f.User)
                .ToList();

            return View(new PostsTag
                {
                    Tag = tag,
                    Posts = new PagedData<Post>(posts, totalPostCount, page, PostsPerPage)
                });
        }

        public ActionResult Show(string idAndSlug)
        {
            var parts = SeperateIdAndSlug(idAndSlug);

            if (parts == null)
                return HttpNotFound();

            var post = Database.Session.Load<Post>(parts.Item1);

            if (post == null || post.IsDeleted)
                return HttpNotFound();

            //if an invalid slug is provided for any reason, redirect to the correct slug
            if (!post.Slug.Equals(parts.Item2, StringComparison.CurrentCultureIgnoreCase))
                return RedirectToRoutePermanent("Post", new { id = parts.Item1, slug = post.Slug });

            return View(new PostsShow
            {
                Post = post
            });
        }


        private System.Tuple<int, string> SeperateIdAndSlug(string idAndSlug)
        {
            var matches = Regex.Match(idAndSlug, @"^(\d+)\-(.*)?$");

            if (!matches.Success)
                return null;

            var id = int.Parse(matches.Result("$1"));
            var slug = matches.Result("$2");

            return System.Tuple.Create(id, slug);
        }
    }
}

Personal Blog Management System/Areas/Admin/Views/Posts/Form.cshtml
@model PersonalBlogManagementSystem.Areas.Admin.ViewModels.PostsForm

@{
    ViewBag.Title = "Form";
}

<h2>@(Model.IsNew ? "Create Post" : "Update Post")</h2>

@using (Html.BeginForm("Form", "Posts"))
{
    if (!Model.IsNew)
    {
        @Html.HiddenFor(f => f.PostId)
    }

    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-lg-8">
            @Html.ValidationSummary()

            <div class="form-group">
                @Html.LabelFor(f => f.Title)
                @Html.TextBoxFor(f => f.Title, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(f => f.Slug)
                @Html.TextBoxFor(f => f.Slug, new { @class = "form-control", data_slug = "#Title" })
            </div>

            <div class="form-group">
                @Html.LabelFor(f => f.Content)
                @Html.TextAreaFor(f => f.Content, new { @class = "form-control" })
            </div>
        </div>

        <div class="col-lg-4">
            <div class="panel panel-info">
                <div class="panel-heading">Post Actions</div>
                <div class="panel-body">
                    <input type="submit" value="@(Model.IsNew ? "Publish Post" : "Update Post")" class="btn btn-success btn-sm" />
                    <a href="@Url.Action("index")">or cancel</a>
                </div>
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">Tags</div>
                <div class="panel-body post-tag-editor">
                    <label for="new-tag-name">New Tag:</label>
                    <div class="input-group">
                        <input id="new-tag-name" type="text" class="new-tag-name form-control" />
                        <span class="input-group-btn">
                            <button disabled class="btn btn-primary add-tag-button">Add</button>
                        </span>
                    </div>

                    <ul class="tag-select">
                        <li class="template">
                            <a href="#" class="name"></a>
                            <input type="hidden" class="name-input" />
                            <input type="hidden" class="selected-input" />
                        </li>

                        @for (var i = 0; i < Model.Tags.Count; i++)
                        {
                            var tag = Model.Tags[i];
                            
                            <li data-tag-id="@tag.Id" class="@(tag.IsChecked ? "selected" : "")">
                                <a href="#">@tag.Name</a>

                                <input type="hidden" name="Tags[@(i)].Id" value="@tag.Id" />
                                <input type="hidden" name="Tags[@(i)].Name" value="@tag.Name" />
                                <input type="hidden" name="Tags[@(i)].IsChecked" value="@tag.IsChecked.ToString()" class="selected-input" />
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts
{
    @System.Web.Optimization.Scripts.Render("~/adminscripts/posts")
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace("Content");
    </script>
}

Personal Blog Management System/Areas/Admin/Views/Posts/Index.cshtml
@model PersonalBlogManagementSystem.Areas.Admin.ViewModels.PostsIndex

@{
    ViewBag.Title = "Index";
}

<h1>Posts</h1>

<div class="btn-toolbar">
    <div class="btn-group">
        <a href="@Url.Action("new")" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-plus"></i> Create Post</a>
    </div>

    <div class="btn-group pull-right">
        @if (Model.Posts.HasPreviousPage)
        {
            <a href="@Url.Action("Index", new { page = Model.Posts.PreviousPage } )" class="btn btn-primary btn-sm">
                <i class="glyphicon glyphicon-chevron-left"></i> Previous Page
            </a>
        }
        else
        {
            <a href="#" class="btn btn-default disabled btn-sm">
                <i class="glyphicon glyphicon-chevron-left"></i> Previous Page
            </a> 
        }

        @if (Model.Posts.HasNextPage)
        {
            <a href="@Url.Action("Index", new { page = Model.Posts.NextPage } )" class="btn btn-primary btn-sm">
               Next Page <i class="glyphicon glyphicon-chevron-right"></i>
            </a>
        }
        else
        {
            <a href="#" class="btn btn-default disabled btn-sm">
               Next Page <i class="glyphicon glyphicon-chevron-right"></i>
            </a>
        }
    </div>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Tags</th>
            <th>Date</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var post in Model.Posts)
        {
            var cls = "";
            if (post.IsDeleted)
            {
                cls = "danger";
            }
            
            <tr class="@cls">
                <td>@post.Title</td>
                <td>@post.User.Username</td>
                <td>@string.Join(", ", post.Tags.Select(t => t.Name))</td>
                <td>@post.Created</td>
                <td>
                    <a href="@Url.Action("edit", new { post.Id })" class="btn btn-xs btn-primary">
                        <i class="glyphicon glyphicon-edit"></i> edit
                    </a>
                    @if (!post.IsDeleted)
                    {
                        <div class="btn-group btn-group-xs">
                            <a href="@Url.Action("trash", new { post.Id })" class="btn btn-danger" data-post="Are you sure you want to trash this post?">
                                <i class="glyphicon glyphicon-remove"></i> Trash
                            </a> 
                            <a href="#" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="@Url.Action("delete", new { post.Id} )" data-post="Are you sure you want to delete this post FOREVER?!">
                                        <i class="glyphicon glyphicon-remove"></i> delete
                                    </a>
                                </li>
                            </ul>
                        </div> 
                    }
                    else
                    {
                        <a href="@Url.Action("restore", new { post.Id })" class="btn btn-xs btn-success" data-post="">
                            <i class="glyphicon glyphicon-plus-sign"></i> restore
                        </a> 
                    }
                </td>
            </tr>
        }
    </tbody>
</table> 