Personal Blog Management System/ViewModels/Layout.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PersonalBlogManagementSystem.ViewModels
{
    public class SidebarTag
    {
        public int Id { get; private set; }
        public string Name { get; private set; }
        public string Slug { get; private set; }
        public int PostCount { get; private set; }

        public SidebarTag(int id, string name, string slug, int postCount)
        {
            Id = id;
            Name = name;
            Slug = slug;
            PostCount = postCount;
        }
    }

    public class LayoutSidebar
    {
        public bool IsLoggedIn { get; set; }
        public string Username { get; set; }
        public bool IsAdmin { get; set; }
        public IEnumerable<SidebarTag> Tags { get; set; }
    }
}

Personal Blog Management System/Areas/Admin/Controllers/LayoutController.cs
using System.Web.Mvc;

namespace PersonalBlogManagementSystem.Areas.Admin.Controllers
{
    public class LayoutController : Controller
    {
        [ChildActionOnly]
        public ActionResult Sidebar()
        {
            return View();
        }
	}
}

Personal Blog Management System/Controllers/LayoutController.cs
using System.Web.Mvc;
using PersonalBlogManagementSystem.ViewModels;
using System.Linq;
using NHibernate.Linq;
using PersonalBlogManagementSystem.Models;

namespace PersonalBlogManagementSystem.Controllers
{
    public class LayoutController : Controller
    {
        [ChildActionOnly]
        public ActionResult Sidebar()
        {
            return View(new LayoutSidebar
            {
                IsLoggedIn = Auth.User != null,
                Username = Auth.User != null ? Auth.User.Username : "",
                IsAdmin = User.IsInRole("admin"),
                Tags = Database.Session.Query<Tag>()
                    .Select(tag => new
                    {
                        tag.Id,
                        tag.Name,
                        tag.Slug,
                        PostCount = tag.Posts.Count
                    })
                    .Where(t => t.PostCount > 0)
                    .OrderByDescending(t => t.PostCount)
                    .Select(tag => new SidebarTag
                    (
                        tag.Id,
                        tag.Name,
                        tag.Slug,
                        tag.PostCount
                    ))
                    .ToList()
            });
        }
	}
}

Personal Blog Management System/Areas/Admin/Views/Shared/_Layout.cshtml
@using System.Web.Optimization

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Personal Blog Admin</title>

    @Styles.Render("~/styles")
    @Styles.Render("~/admin/styles")
</head>
<body>
    <div class="site-header">
        <header class="container">
            <h1 class="page-header col-lg-8">
                <a href="@Url.RouteUrl("Home")">My Blog</a>
                <small>a simple blog powered by ASP.NET MVC</small>
            </h1>
            @if (!HttpContext.Current.User.Identity.IsAuthenticated)
            {
                <div class="pull-right">
                    <a href="@Url.RouteUrl("Login")" class="btn btn-lg btn-success btn-login">Login</a>
                </div>
            }
            else
            {
                <div class="pull-right">
                    <a href="@Url.RouteUrl("Logout")" class="btn btn-lg btn-danger btn-login">Logout</a>
                </div>
            }
        </header>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                @RenderBody()
            </div>
            <div class="col-lg-4 sidebar">
                @Html.Action("Sidebar", "Layout")
            </div>
        </div>

        <footer>
            &copy; @DateTime.UtcNow.Year
        </footer>
    </div>
   

    @Scripts.Render("~/allscripts")
    @Scripts.Render("~/adminscripts")
    @RenderSection("Scripts", false)

    <form class="hidden" id="hdn-anti-forgery-form">
        @Html.AntiForgeryToken()
    </form>





    
</body>
</html>